#
#
#
#

# ROS-1:
#uint32 uiIdent             # Logical number of the device"
#uint32 udiSerialNo         # Serial number of the device
#bool bDeviceError          # State of the device
#bool bContaminationWarning # Contamination Warning
#bool bContaminationError   # Contamination Error

# ROS-2:
uint32 uiident             # Logical number of the device"
uint32 udiserialno         # Serial number of the device
bool bdeviceerror          # State of the device
bool bcontaminationwarning # Contamination Warning
bool bcontaminationerror   # Contamination Error
