#
#
#
# ROS-1:
#uint32 uiTelegramCount # telegram number
#uint32 uiCycleCount # "scan number"
#uint32 udiSystemCountScan # system time since power on of scan gen. [us]
#uint32 udiSystemCountTransmit # system time since power on of scan transmission [us]
#uint16 uiInputs # state of digital inputs
#uint16 uiOutputs # state of digital outputs

# ROS-2:
uint32 uitelegramcount # telegram number
uint32 uicyclecount # "scan number"
uint32 udisystemcountscan # system time since power on of scan gen. [us]
uint32 udisystemcounttransmit # system time since power on of scan transmission [us]
uint16 uiinputs # state of digital inputs
uint16 uioutputs # state of digital outputs
