// Generated by gencpp from file sick_scan/LIDoutputstateSrvRequest.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_LIDOUTPUTSTATESRVREQUEST_H
#define SICK_SCAN_MESSAGE_LIDOUTPUTSTATESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sick_scan
{
template <class ContainerAllocator>
struct LIDoutputstateSrvRequest_
{
  typedef LIDoutputstateSrvRequest_<ContainerAllocator> Type;

  LIDoutputstateSrvRequest_()
    : active(false)  {
    }
  LIDoutputstateSrvRequest_(const ContainerAllocator& _alloc)
    : active(false)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LIDoutputstateSrvRequest_

typedef ::sick_scan::LIDoutputstateSrvRequest_<std::allocator<void> > LIDoutputstateSrvRequest;

typedef boost::shared_ptr< ::sick_scan::LIDoutputstateSrvRequest > LIDoutputstateSrvRequestPtr;
typedef boost::shared_ptr< ::sick_scan::LIDoutputstateSrvRequest const> LIDoutputstateSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator1> & lhs, const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.active == rhs.active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator1> & lhs, const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sick_scan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c5cfb0a2565df41de6873994aee57d2";
  }

  static const char* value(const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c5cfb0a2565df41ULL;
  static const uint64_t static_value2 = 0xde6873994aee57d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_scan/LIDoutputstateSrvRequest";
  }

  static const char* value(const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Definition of ROS service LIDoutputstate for sick_scan\n"
"# Start or stop Send outputstate by event\n"
"# Example call (ROS1):\n"
"# rosservice call /sick_tim_7xx/LIDoutputstate \"{active: 1}\"\n"
"# \n"
"\n"
"# \n"
"# Request (input)\n"
"# \n"
"\n"
"bool active # start/stop send outputstate by event\n"
"\n"
;
  }

  static const char* value(const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LIDoutputstateSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_scan::LIDoutputstateSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SICK_SCAN_MESSAGE_LIDOUTPUTSTATESRVREQUEST_H
