// Generated by gencpp from file sick_scan/SCsoftresetSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SCSOFTRESETSRV_H
#define SICK_SCAN_MESSAGE_SCSOFTRESETSRV_H

#include <ros/service_traits.h>


#include <sick_scan/SCsoftresetSrvRequest.h>
#include <sick_scan/SCsoftresetSrvResponse.h>


namespace sick_scan
{

struct SCsoftresetSrv
{

typedef SCsoftresetSrvRequest Request;
typedef SCsoftresetSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SCsoftresetSrv
} // namespace sick_scan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan::SCsoftresetSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_scan::SCsoftresetSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan::SCsoftresetSrv > {
  static const char* value()
  {
    return "sick_scan/SCsoftresetSrv";
  }

  static const char* value(const ::sick_scan::SCsoftresetSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan::SCsoftresetSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan::SCsoftresetSrv >
template<>
struct MD5Sum< ::sick_scan::SCsoftresetSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SCsoftresetSrv >::value();
  }
  static const char* value(const ::sick_scan::SCsoftresetSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SCsoftresetSrvRequest> should match
// service_traits::DataType< ::sick_scan::SCsoftresetSrv >
template<>
struct DataType< ::sick_scan::SCsoftresetSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SCsoftresetSrv >::value();
  }
  static const char* value(const ::sick_scan::SCsoftresetSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan::SCsoftresetSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan::SCsoftresetSrv >
template<>
struct MD5Sum< ::sick_scan::SCsoftresetSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SCsoftresetSrv >::value();
  }
  static const char* value(const ::sick_scan::SCsoftresetSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SCsoftresetSrvResponse> should match
// service_traits::DataType< ::sick_scan::SCsoftresetSrv >
template<>
struct DataType< ::sick_scan::SCsoftresetSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SCsoftresetSrv >::value();
  }
  static const char* value(const ::sick_scan::SCsoftresetSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_SCAN_MESSAGE_SCSOFTRESETSRV_H
