#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocInitialPoseSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCINITIALPOSESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCINITIALPOSESRV_H

#include <ros/service_traits.h>


#include <sick_scan/SickLocInitialPoseSrvRequest.h>
#include <sick_scan/SickLocInitialPoseSrvResponse.h>


namespace sick_scan
{

struct SickLocInitialPoseSrv
{

typedef SickLocInitialPoseSrvRequest Request;
typedef SickLocInitialPoseSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocInitialPoseSrv
} // namespace sick_scan


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan::SickLocInitialPoseSrv > {
  static const char* value()
  {
    return "4fe0365a98e851d2ec605133b8bf8e0f";
  }

  static const char* value(const ::sick_scan::SickLocInitialPoseSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan::SickLocInitialPoseSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocInitialPoseSrv";
  }

  static const char* value(const ::sick_scan::SickLocInitialPoseSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan::SickLocInitialPoseSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan::SickLocInitialPoseSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocInitialPoseSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocInitialPoseSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocInitialPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocInitialPoseSrvRequest> should match
// service_traits::DataType< ::sick_scan::SickLocInitialPoseSrv >
template<>
struct DataType< ::sick_scan::SickLocInitialPoseSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocInitialPoseSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocInitialPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan::SickLocInitialPoseSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan::SickLocInitialPoseSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocInitialPoseSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocInitialPoseSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocInitialPoseSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocInitialPoseSrvResponse> should match
// service_traits::DataType< ::sick_scan::SickLocInitialPoseSrv >
template<>
struct DataType< ::sick_scan::SickLocInitialPoseSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocInitialPoseSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocInitialPoseSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCINITIALPOSESRV_H
