#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocResultStateSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCRESULTSTATESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCRESULTSTATESRV_H

#include <ros/service_traits.h>


#include <sick_scan/SickLocResultStateSrvRequest.h>
#include <sick_scan/SickLocResultStateSrvResponse.h>


namespace sick_scan
{

struct SickLocResultStateSrv
{

typedef SickLocResultStateSrvRequest Request;
typedef SickLocResultStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocResultStateSrv
} // namespace sick_scan


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan::SickLocResultStateSrv > {
  static const char* value()
  {
    return "9c5ad6cfbe3078e7136569fb578473b6";
  }

  static const char* value(const ::sick_scan::SickLocResultStateSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan::SickLocResultStateSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocResultStateSrv";
  }

  static const char* value(const ::sick_scan::SickLocResultStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan::SickLocResultStateSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan::SickLocResultStateSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocResultStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocResultStateSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocResultStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocResultStateSrvRequest> should match
// service_traits::DataType< ::sick_scan::SickLocResultStateSrv >
template<>
struct DataType< ::sick_scan::SickLocResultStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocResultStateSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocResultStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan::SickLocResultStateSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan::SickLocResultStateSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocResultStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocResultStateSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocResultStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocResultStateSrvResponse> should match
// service_traits::DataType< ::sick_scan::SickLocResultStateSrv >
template<>
struct DataType< ::sick_scan::SickLocResultStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocResultStateSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocResultStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCRESULTSTATESRV_H
