#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocSetRingBufferRecordingActiveSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSETRINGBUFFERRECORDINGACTIVESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCSETRINGBUFFERRECORDINGACTIVESRV_H

#include <ros/service_traits.h>


#include <sick_scan/SickLocSetRingBufferRecordingActiveSrvRequest.h>
#include <sick_scan/SickLocSetRingBufferRecordingActiveSrvResponse.h>


namespace sick_scan
{

struct SickLocSetRingBufferRecordingActiveSrv
{

typedef SickLocSetRingBufferRecordingActiveSrvRequest Request;
typedef SickLocSetRingBufferRecordingActiveSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetRingBufferRecordingActiveSrv
} // namespace sick_scan


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv > {
  static const char* value()
  {
    return "83465e5956f4615e09223f5d055d1f12";
  }

  static const char* value(const ::sick_scan::SickLocSetRingBufferRecordingActiveSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocSetRingBufferRecordingActiveSrv";
  }

  static const char* value(const ::sick_scan::SickLocSetRingBufferRecordingActiveSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocSetRingBufferRecordingActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvRequest> should match
// service_traits::DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >
template<>
struct DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocSetRingBufferRecordingActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocSetRingBufferRecordingActiveSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvResponse> should match
// service_traits::DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >
template<>
struct DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocSetRingBufferRecordingActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocSetRingBufferRecordingActiveSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSETRINGBUFFERRECORDINGACTIVESRV_H
