#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickDevIMUActiveSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKDEVIMUACTIVESRV_H
#define SICK_SCAN_MESSAGE_SICKDEVIMUACTIVESRV_H

#include <ros/service_traits.h>


#include <sick_scan/SickDevIMUActiveSrvRequest.h>
#include <sick_scan/SickDevIMUActiveSrvResponse.h>


namespace sick_scan
{

struct SickDevIMUActiveSrv
{

typedef SickDevIMUActiveSrvRequest Request;
typedef SickDevIMUActiveSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickDevIMUActiveSrv
} // namespace sick_scan


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan::SickDevIMUActiveSrv > {
  static const char* value()
  {
    return "9bb3f90ef7a4dde50a9193067d4298d5";
  }

  static const char* value(const ::sick_scan::SickDevIMUActiveSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan::SickDevIMUActiveSrv > {
  static const char* value()
  {
    return "sick_scan/SickDevIMUActiveSrv";
  }

  static const char* value(const ::sick_scan::SickDevIMUActiveSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan::SickDevIMUActiveSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan::SickDevIMUActiveSrv >
template<>
struct MD5Sum< ::sick_scan::SickDevIMUActiveSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickDevIMUActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickDevIMUActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickDevIMUActiveSrvRequest> should match
// service_traits::DataType< ::sick_scan::SickDevIMUActiveSrv >
template<>
struct DataType< ::sick_scan::SickDevIMUActiveSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickDevIMUActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickDevIMUActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan::SickDevIMUActiveSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan::SickDevIMUActiveSrv >
template<>
struct MD5Sum< ::sick_scan::SickDevIMUActiveSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickDevIMUActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickDevIMUActiveSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickDevIMUActiveSrvResponse> should match
// service_traits::DataType< ::sick_scan::SickDevIMUActiveSrv >
template<>
struct DataType< ::sick_scan::SickDevIMUActiveSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickDevIMUActiveSrv >::value();
  }
  static const char* value(const ::sick_scan::SickDevIMUActiveSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKDEVIMUACTIVESRV_H
