#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocMapSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCMAPSRV_H
#define SICK_SCAN_MESSAGE_SICKLOCMAPSRV_H

#include <ros/service_traits.h>


#include <sick_scan/SickLocMapSrvRequest.h>
#include <sick_scan/SickLocMapSrvResponse.h>


namespace sick_scan
{

struct SickLocMapSrv
{

typedef SickLocMapSrvRequest Request;
typedef SickLocMapSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocMapSrv
} // namespace sick_scan


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan::SickLocMapSrv > {
  static const char* value()
  {
    return "aa2a9f1d383f960de835b664a64ecd21";
  }

  static const char* value(const ::sick_scan::SickLocMapSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan::SickLocMapSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocMapSrv";
  }

  static const char* value(const ::sick_scan::SickLocMapSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan::SickLocMapSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan::SickLocMapSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocMapSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocMapSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocMapSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocMapSrvRequest> should match
// service_traits::DataType< ::sick_scan::SickLocMapSrv >
template<>
struct DataType< ::sick_scan::SickLocMapSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocMapSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocMapSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan::SickLocMapSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan::SickLocMapSrv >
template<>
struct MD5Sum< ::sick_scan::SickLocMapSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan::SickLocMapSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocMapSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan::SickLocMapSrvResponse> should match
// service_traits::DataType< ::sick_scan::SickLocMapSrv >
template<>
struct DataType< ::sick_scan::SickLocMapSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan::SickLocMapSrv >::value();
  }
  static const char* value(const ::sick_scan::SickLocMapSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCMAPSRV_H
