#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/ColaMsgSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_COLAMSGSRV_H
#define SICK_SCAN_MESSAGE_COLAMSGSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/ColaMsgSrvRequest.h>
#include <sick_scan_xd/ColaMsgSrvResponse.h>


namespace sick_scan_xd
{

struct ColaMsgSrv
{

typedef ColaMsgSrvRequest Request;
typedef ColaMsgSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ColaMsgSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::ColaMsgSrv > {
  static const char* value()
  {
    return "33ea4e5aeb30f5913da681ca459d55f3";
  }

  static const char* value(const ::sick_scan_xd::ColaMsgSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::ColaMsgSrv > {
  static const char* value()
  {
    return "sick_scan/ColaMsgSrv";
  }

  static const char* value(const ::sick_scan_xd::ColaMsgSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::ColaMsgSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::ColaMsgSrv >
template<>
struct MD5Sum< ::sick_scan_xd::ColaMsgSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::ColaMsgSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ColaMsgSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::ColaMsgSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::ColaMsgSrv >
template<>
struct DataType< ::sick_scan_xd::ColaMsgSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::ColaMsgSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ColaMsgSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::ColaMsgSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::ColaMsgSrv >
template<>
struct MD5Sum< ::sick_scan_xd::ColaMsgSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::ColaMsgSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ColaMsgSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::ColaMsgSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::ColaMsgSrv >
template<>
struct DataType< ::sick_scan_xd::ColaMsgSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::ColaMsgSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ColaMsgSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_COLAMSGSRV_H
