#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/ECRChangeArrSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_ECRCHANGEARRSRV_H
#define SICK_SCAN_MESSAGE_ECRCHANGEARRSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/ECRChangeArrSrvRequest.h>
#include <sick_scan_xd/ECRChangeArrSrvResponse.h>


namespace sick_scan_xd
{

struct ECRChangeArrSrv
{

typedef ECRChangeArrSrvRequest Request;
typedef ECRChangeArrSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ECRChangeArrSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::ECRChangeArrSrv > {
  static const char* value()
  {
    return "83465e5956f4615e09223f5d055d1f12";
  }

  static const char* value(const ::sick_scan_xd::ECRChangeArrSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::ECRChangeArrSrv > {
  static const char* value()
  {
    return "sick_scan/ECRChangeArrSrv";
  }

  static const char* value(const ::sick_scan_xd::ECRChangeArrSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::ECRChangeArrSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::ECRChangeArrSrv >
template<>
struct MD5Sum< ::sick_scan_xd::ECRChangeArrSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::ECRChangeArrSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ECRChangeArrSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::ECRChangeArrSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::ECRChangeArrSrv >
template<>
struct DataType< ::sick_scan_xd::ECRChangeArrSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::ECRChangeArrSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ECRChangeArrSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::ECRChangeArrSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::ECRChangeArrSrv >
template<>
struct MD5Sum< ::sick_scan_xd::ECRChangeArrSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::ECRChangeArrSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ECRChangeArrSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::ECRChangeArrSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::ECRChangeArrSrv >
template<>
struct DataType< ::sick_scan_xd::ECRChangeArrSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::ECRChangeArrSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::ECRChangeArrSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_ECRCHANGEARRSRV_H
