#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan_xd/GetContaminationDataSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_XD_MESSAGE_GETCONTAMINATIONDATASRV_H
#define SICK_SCAN_XD_MESSAGE_GETCONTAMINATIONDATASRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/GetContaminationDataSrvRequest.h>
#include <sick_scan_xd/GetContaminationDataSrvResponse.h>


namespace sick_scan_xd
{

struct GetContaminationDataSrv
{

typedef GetContaminationDataSrvRequest Request;
typedef GetContaminationDataSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetContaminationDataSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::GetContaminationDataSrv > {
  static const char* value()
  {
    return "ffedec9c51bebb63c0cc55e8fa1eba38";
  }

  static const char* value(const ::sick_scan_xd::GetContaminationDataSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::GetContaminationDataSrv > {
  static const char* value()
  {
    return "sick_scan_xd/GetContaminationDataSrv";
  }

  static const char* value(const ::sick_scan_xd::GetContaminationDataSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::GetContaminationDataSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::GetContaminationDataSrv >
template<>
struct MD5Sum< ::sick_scan_xd::GetContaminationDataSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::GetContaminationDataSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::GetContaminationDataSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::GetContaminationDataSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::GetContaminationDataSrv >
template<>
struct DataType< ::sick_scan_xd::GetContaminationDataSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::GetContaminationDataSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::GetContaminationDataSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::GetContaminationDataSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::GetContaminationDataSrv >
template<>
struct MD5Sum< ::sick_scan_xd::GetContaminationDataSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::GetContaminationDataSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::GetContaminationDataSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::GetContaminationDataSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::GetContaminationDataSrv >
template<>
struct DataType< ::sick_scan_xd::GetContaminationDataSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::GetContaminationDataSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::GetContaminationDataSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_XD_MESSAGE_GETCONTAMINATIONDATASRV_H
