#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocAutoStartActiveSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCAUTOSTARTACTIVESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCAUTOSTARTACTIVESRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocAutoStartActiveSrvRequest.h>
#include <sick_scan_xd/SickLocAutoStartActiveSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocAutoStartActiveSrv
{

typedef SickLocAutoStartActiveSrvRequest Request;
typedef SickLocAutoStartActiveSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocAutoStartActiveSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrv > {
  static const char* value()
  {
    return "9bb3f90ef7a4dde50a9193067d4298d5";
  }

  static const char* value(const ::sick_scan_xd::SickLocAutoStartActiveSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocAutoStartActiveSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocAutoStartActiveSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocAutoStartActiveSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartActiveSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartActiveSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocAutoStartActiveSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocAutoStartActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocAutoStartActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartActiveSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartActiveSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartActiveSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocAutoStartActiveSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocAutoStartActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartActiveSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCAUTOSTARTACTIVESRV_H
