#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocStartDemoMappingSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSTARTDEMOMAPPINGSRV_H
#define SICK_SCAN_MESSAGE_SICKLOCSTARTDEMOMAPPINGSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocStartDemoMappingSrvRequest.h>
#include <sick_scan_xd/SickLocStartDemoMappingSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocStartDemoMappingSrv
{

typedef SickLocStartDemoMappingSrvRequest Request;
typedef SickLocStartDemoMappingSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocStartDemoMappingSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_scan_xd::SickLocStartDemoMappingSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocStartDemoMappingSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocStartDemoMappingSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocStartDemoMappingSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartDemoMappingSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocStartDemoMappingSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocStartDemoMappingSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocStartDemoMappingSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocStartDemoMappingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartDemoMappingSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocStartDemoMappingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartDemoMappingSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocStartDemoMappingSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocStartDemoMappingSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocStartDemoMappingSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocStartDemoMappingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartDemoMappingSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSTARTDEMOMAPPINGSRV_H
