#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocInitializePoseSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCINITIALIZEPOSESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCINITIALIZEPOSESRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocInitializePoseSrvRequest.h>
#include <sick_scan_xd/SickLocInitializePoseSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocInitializePoseSrv
{

typedef SickLocInitializePoseSrvRequest Request;
typedef SickLocInitializePoseSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocInitializePoseSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrv > {
  static const char* value()
  {
    return "dee1d4e0c5989710a3df581b09da8483";
  }

  static const char* value(const ::sick_scan_xd::SickLocInitializePoseSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocInitializePoseSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocInitializePoseSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocInitializePoseSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocInitializePoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocInitializePoseSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocInitializePoseSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocInitializePoseSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocInitializePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocInitializePoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocInitializePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocInitializePoseSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocInitializePoseSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocInitializePoseSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocInitializePoseSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocInitializePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocInitializePoseSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCINITIALIZEPOSESRV_H
