#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocAutoStartSavePoseSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCAUTOSTARTSAVEPOSESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCAUTOSTARTSAVEPOSESRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocAutoStartSavePoseSrvRequest.h>
#include <sick_scan_xd/SickLocAutoStartSavePoseSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocAutoStartSavePoseSrv
{

typedef SickLocAutoStartSavePoseSrvRequest Request;
typedef SickLocAutoStartSavePoseSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocAutoStartSavePoseSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_scan_xd::SickLocAutoStartSavePoseSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocAutoStartSavePoseSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocAutoStartSavePoseSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartSavePoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartSavePoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartSavePoseSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocAutoStartSavePoseSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocAutoStartSavePoseSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCAUTOSTARTSAVEPOSESRV_H
