#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocSetOdometryRestrictYMotionSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSETODOMETRYRESTRICTYMOTIONSRV_H
#define SICK_SCAN_MESSAGE_SICKLOCSETODOMETRYRESTRICTYMOTIONSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocSetOdometryRestrictYMotionSrvRequest.h>
#include <sick_scan_xd/SickLocSetOdometryRestrictYMotionSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocSetOdometryRestrictYMotionSrv
{

typedef SickLocSetOdometryRestrictYMotionSrvRequest Request;
typedef SickLocSetOdometryRestrictYMotionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetOdometryRestrictYMotionSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv > {
  static const char* value()
  {
    return "83465e5956f4615e09223f5d055d1f12";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocSetOdometryRestrictYMotionSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetOdometryRestrictYMotionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSETODOMETRYRESTRICTYMOTIONSRV_H
