#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocForceUpdateSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCFORCEUPDATESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCFORCEUPDATESRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocForceUpdateSrvRequest.h>
#include <sick_scan_xd/SickLocForceUpdateSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocForceUpdateSrv
{

typedef SickLocForceUpdateSrvRequest Request;
typedef SickLocForceUpdateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocForceUpdateSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_scan_xd::SickLocForceUpdateSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocForceUpdateSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocForceUpdateSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocForceUpdateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocForceUpdateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocForceUpdateSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocForceUpdateSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocForceUpdateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocForceUpdateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocForceUpdateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocForceUpdateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocForceUpdateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocForceUpdateSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocForceUpdateSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocForceUpdateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocForceUpdateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocForceUpdateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCFORCEUPDATESRV_H
