#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickDevGetLidarStateSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKDEVGETLIDARSTATESRV_H
#define SICK_SCAN_MESSAGE_SICKDEVGETLIDARSTATESRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickDevGetLidarStateSrvRequest.h>
#include <sick_scan_xd/SickDevGetLidarStateSrvResponse.h>


namespace sick_scan_xd
{

struct SickDevGetLidarStateSrv
{

typedef SickDevGetLidarStateSrvRequest Request;
typedef SickDevGetLidarStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickDevGetLidarStateSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrv > {
  static const char* value()
  {
    return "4e9cd340bdbbe8fa461bfa3199907f21";
  }

  static const char* value(const ::sick_scan_xd::SickDevGetLidarStateSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickDevGetLidarStateSrv > {
  static const char* value()
  {
    return "sick_scan/SickDevGetLidarStateSrv";
  }

  static const char* value(const ::sick_scan_xd::SickDevGetLidarStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickDevGetLidarStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickDevGetLidarStateSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickDevGetLidarStateSrv >
template<>
struct DataType< ::sick_scan_xd::SickDevGetLidarStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickDevGetLidarStateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickDevGetLidarStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickDevGetLidarStateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickDevGetLidarStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickDevGetLidarStateSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickDevGetLidarStateSrv >
template<>
struct DataType< ::sick_scan_xd::SickDevGetLidarStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickDevGetLidarStateSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickDevGetLidarStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKDEVGETLIDARSTATESRV_H
