#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickScanExitSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKSCANEXITSRV_H
#define SICK_SCAN_MESSAGE_SICKSCANEXITSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickScanExitSrvRequest.h>
#include <sick_scan_xd/SickScanExitSrvResponse.h>


namespace sick_scan_xd
{

struct SickScanExitSrv
{

typedef SickScanExitSrvRequest Request;
typedef SickScanExitSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickScanExitSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickScanExitSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_scan_xd::SickScanExitSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickScanExitSrv > {
  static const char* value()
  {
    return "sick_scan/SickScanExitSrv";
  }

  static const char* value(const ::sick_scan_xd::SickScanExitSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickScanExitSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickScanExitSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickScanExitSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickScanExitSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickScanExitSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickScanExitSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickScanExitSrv >
template<>
struct DataType< ::sick_scan_xd::SickScanExitSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickScanExitSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickScanExitSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickScanExitSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickScanExitSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickScanExitSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickScanExitSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickScanExitSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickScanExitSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickScanExitSrv >
template<>
struct DataType< ::sick_scan_xd::SickScanExitSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickScanExitSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickScanExitSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKSCANEXITSRV_H
