#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocSetResultPoseIntervalSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSETRESULTPOSEINTERVALSRV_H
#define SICK_SCAN_MESSAGE_SICKLOCSETRESULTPOSEINTERVALSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocSetResultPoseIntervalSrvRequest.h>
#include <sick_scan_xd/SickLocSetResultPoseIntervalSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocSetResultPoseIntervalSrv
{

typedef SickLocSetResultPoseIntervalSrvRequest Request;
typedef SickLocSetResultPoseIntervalSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetResultPoseIntervalSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv > {
  static const char* value()
  {
    return "dfed1807f9eafde8783e0a05f0ca7dce";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetResultPoseIntervalSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocSetResultPoseIntervalSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetResultPoseIntervalSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPoseIntervalSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPoseIntervalSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPoseIntervalSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocSetResultPoseIntervalSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPoseIntervalSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSETRESULTPOSEINTERVALSRV_H
