#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocSetResultPortSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSETRESULTPORTSRV_H
#define SICK_SCAN_MESSAGE_SICKLOCSETRESULTPORTSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocSetResultPortSrvRequest.h>
#include <sick_scan_xd/SickLocSetResultPortSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocSetResultPortSrv
{

typedef SickLocSetResultPortSrvRequest Request;
typedef SickLocSetResultPortSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocSetResultPortSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrv > {
  static const char* value()
  {
    return "22d338505934787b6445bcb45da196e0";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetResultPortSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocSetResultPortSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocSetResultPortSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetResultPortSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPortSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPortSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPortSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocSetResultPortSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPortSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPortSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPortSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocSetResultPortSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocSetResultPortSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocSetResultPortSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocSetResultPortSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSETRESULTPORTSRV_H
