#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocSetAutoStartSavePoseIntervalSrvRequest.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSETAUTOSTARTSAVEPOSEINTERVALSRVREQUEST_H
#define SICK_SCAN_MESSAGE_SICKLOCSETAUTOSTARTSAVEPOSEINTERVALSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sick_scan_xd
{
template <class ContainerAllocator>
struct SickLocSetAutoStartSavePoseIntervalSrvRequest_
{
  typedef SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> Type;

  SickLocSetAutoStartSavePoseIntervalSrvRequest_()
    : interval(0)  {
    }
  SickLocSetAutoStartSavePoseIntervalSrvRequest_(const ContainerAllocator& _alloc)
    : interval(0)  {
  (void)_alloc;
    }



   typedef uint32_t _interval_type;
  _interval_type interval;





  typedef std::shared_ptr< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SickLocSetAutoStartSavePoseIntervalSrvRequest_

typedef ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<std::allocator<void> > SickLocSetAutoStartSavePoseIntervalSrvRequest;

typedef std::shared_ptr< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest > SickLocSetAutoStartSavePoseIntervalSrvRequestPtr;
typedef std::shared_ptr< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest const> SickLocSetAutoStartSavePoseIntervalSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator1> & lhs, const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.interval == rhs.interval;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator1> & lhs, const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sick_scan_xd

namespace roswrap
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06b48bd7e58b12d956f88d61f7bee8e0";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06b48bd7e58b12d9ULL;
  static const uint64_t static_value2 = 0x56f88d61f7bee8e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_scan/SickLocSetAutoStartSavePoseIntervalSrvRequest";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Definition of ROS service SickLocSetAutoStartSavePoseInterval for sick localization\n"
"# Set the interval in seconds for saving the pose automatically for auto start while localizing\n"
"# Example call (ROS1):\n"
"# rosservice call SickLocSetAutoStartSavePoseInterval \"{interval: 1}\"\n"
"# Example call (ROS2):\n"
"# ros2 service call SickLocSetAutoStartSavePoseInterval sick_scan/srv/SickLocSetAutoStartSavePoseIntervalSrv \"{interval: 1}\"\n"
"# \n"
"\n"
"# \n"
"# Request (input)\n"
"# \n"
"\n"
"uint32 interval # Interval between consecutive pose saving in seconds. [<min>, <max>] \n"
"\n"
;
  }

  static const char* value(const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace roswrap

namespace roswrap
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.interval);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SickLocSetAutoStartSavePoseIntervalSrvRequest_

} // namespace serialization
} // namespace roswrap

namespace roswrap
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_scan_xd::SickLocSetAutoStartSavePoseIntervalSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "interval: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.interval);
  }
};

} // namespace message_operations
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSETAUTOSTARTSAVEPOSEINTERVALSRVREQUEST_H
