#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocStartLocalizingSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSTARTLOCALIZINGSRV_H
#define SICK_SCAN_MESSAGE_SICKLOCSTARTLOCALIZINGSRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocStartLocalizingSrvRequest.h>
#include <sick_scan_xd/SickLocStartLocalizingSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocStartLocalizingSrv
{

typedef SickLocStartLocalizingSrvRequest Request;
typedef SickLocStartLocalizingSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocStartLocalizingSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::sick_scan_xd::SickLocStartLocalizingSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocStartLocalizingSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocStartLocalizingSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocStartLocalizingSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartLocalizingSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocStartLocalizingSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocStartLocalizingSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocStartLocalizingSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartLocalizingSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartLocalizingSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocStartLocalizingSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocStartLocalizingSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocStartLocalizingSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocStartLocalizingSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocStartLocalizingSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSTARTLOCALIZINGSRV_H
