#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocSetOdometryActiveSrvRequest.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCSETODOMETRYACTIVESRVREQUEST_H
#define SICK_SCAN_MESSAGE_SICKLOCSETODOMETRYACTIVESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sick_scan_xd
{
template <class ContainerAllocator>
struct SickLocSetOdometryActiveSrvRequest_
{
  typedef SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> Type;

  SickLocSetOdometryActiveSrvRequest_()
    : active(false)  {
    }
  SickLocSetOdometryActiveSrvRequest_(const ContainerAllocator& _alloc)
    : active(false)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;





  typedef std::shared_ptr< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> > Ptr;
  typedef std::shared_ptr< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SickLocSetOdometryActiveSrvRequest_

typedef ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<std::allocator<void> > SickLocSetOdometryActiveSrvRequest;

typedef std::shared_ptr< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest > SickLocSetOdometryActiveSrvRequestPtr;
typedef std::shared_ptr< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest const> SickLocSetOdometryActiveSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator1> & lhs, const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.active == rhs.active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator1> & lhs, const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sick_scan_xd

namespace roswrap
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c5cfb0a2565df41de6873994aee57d2";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c5cfb0a2565df41ULL;
  static const uint64_t static_value2 = 0xde6873994aee57d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_scan/SickLocSetOdometryActiveSrvRequest";
  }

  static const char* value(const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Definition of ROS service SickLocSetOdometryActive for sick localization\n"
"# Enables or disables usage of odometry data in Scan Matching\n"
"# Example call (ROS1):\n"
"# rosservice call SickLocSetOdometryActive \"{active: 1}\"\n"
"# Example call (ROS2):\n"
"# ros2 service call SickLocSetOdometryActive sick_scan/srv/SickLocSetOdometryActiveSrv \"{active: 1}\"\n"
"# \n"
"\n"
"# \n"
"# Request (input)\n"
"# \n"
"\n"
"bool active # Whether data from an odometry sensor is considered in Scan Matching {0 (false), 1 (true)} \n"
"\n"
;
  }

  static const char* value(const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace roswrap

namespace roswrap
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SickLocSetOdometryActiveSrvRequest_

} // namespace serialization
} // namespace roswrap

namespace roswrap
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_scan_xd::SickLocSetOdometryActiveSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
  }
};

} // namespace message_operations
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCSETODOMETRYACTIVESRVREQUEST_H
