#include "sick_scan/sick_scan_base.h" /* Base definitions included in all header files, added by add_sick_scan_base_header.py. Do not edit this line. */
// Generated by gencpp from file sick_scan/SickLocReflectorsForSupportActiveSrv.msg
// DO NOT EDIT!


#ifndef SICK_SCAN_MESSAGE_SICKLOCREFLECTORSFORSUPPORTACTIVESRV_H
#define SICK_SCAN_MESSAGE_SICKLOCREFLECTORSFORSUPPORTACTIVESRV_H

#include <ros/service_traits.h>


#include <sick_scan_xd/SickLocReflectorsForSupportActiveSrvRequest.h>
#include <sick_scan_xd/SickLocReflectorsForSupportActiveSrvResponse.h>


namespace sick_scan_xd
{

struct SickLocReflectorsForSupportActiveSrv
{

typedef SickLocReflectorsForSupportActiveSrvRequest Request;
typedef SickLocReflectorsForSupportActiveSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SickLocReflectorsForSupportActiveSrv
} // namespace sick_scan_xd


namespace roswrap
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv > {
  static const char* value()
  {
    return "9bb3f90ef7a4dde50a9193067d4298d5";
  }

  static const char* value(const ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv&) { return value(); }
};

template<>
struct DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv > {
  static const char* value()
  {
    return "sick_scan/SickLocReflectorsForSupportActiveSrv";
  }

  static const char* value(const ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvRequest> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvRequest> should match
// service_traits::DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvResponse> should match
// service_traits::MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >
template<>
struct MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvResponse> should match
// service_traits::DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >
template<>
struct DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sick_scan_xd::SickLocReflectorsForSupportActiveSrv >::value();
  }
  static const char* value(const ::sick_scan_xd::SickLocReflectorsForSupportActiveSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace roswrap

#endif // SICK_SCAN_MESSAGE_SICKLOCREFLECTORSFORSUPPORTACTIVESRV_H
