# Definition of ROS service SCdevicestate for sick_scan_xd
# Example call (ROS1):
# rosservice call /sick_tim_7xx/SCdevicestate "{}"
# 

# 
# Request (input)
# 

---

# 
# Response (output)
# 

int32 state # device state: busy:0, ready:1, error:2
bool success # true: success response received from lidar, false: service failed (timeout or error status from controller)
