# Definition of ROS service SCsoftreset for sick_scan_xd
# Example call (ROS1):
# rosservice call /sick_tim_7xx/SCsoftreset "{}"
# 

# 
# Request (input)
# 

---

# 
# Response (output)
# 

bool success # true: success response received from lidar, false: service failed (timeout or error status from controller)
