#
# Select ROS-1 version, e.g. noetic or melodic
#

FROM osrf/ros:noetic-desktop-full

#
# install ROS package
#
RUN apt-get update && apt-get install -y ros-${ROS_DISTRO}-desktop ros-${ROS_DISTRO}-rviz psmisc
RUN rm -rf /var/lib/apt/lists/*

#
# copy or checkout sick_scan_xd to current docker container
#
RUN mkdir -p /workspace/src
COPY ./src /workspace/src/
WORKDIR /workspace

#
# build msgpack11 in docker container
#
RUN /bin/bash -c "mkdir -p ./build/msgpack11 ; pushd ./build/msgpack11 ; cmake -G \"Unix Makefiles\" -D CMAKE_CXX_FLAGS=-fPIC -D CMAKE_BUILD_TYPE=Release -D MSGPACK11_BUILD_TESTS=0 ../../src/msgpack11 ; make ; make install ; popd"

#
# build sick_scan_xd in docker container
#
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash ; catkin_make_isolated --install --cmake-args -DROS_VERSION=1 -DCMAKE_ENABLE_EMULATOR=1 -Wno-dev"
RUN /bin/bash -c "echo -e \"\nsick_scan_xd catkin_make_isolated finished:\" ; ls -al /workspace/install_isolated/lib/sick_scan"

#
# launch ros package, run sick_scan_xd with MRS1104 emulator
#
CMD /bin/bash -c "cd /workspace/src/sick_scan_xd/test/scripts ; ls -al ; ./run_linux_ros1_simu_mrs1104.bash"

